AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket with Parameterized Name and Versioning"

Parameters:
  BucketName:
    Type: String
    Description: Name of the bucket
    Default: Rishikumar-8972657-s3-stack

  VersioningStatus:
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled
    Description: Versioning toggle

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningStatus
      Tags:
        - Key: Owner
          Value: Rishikumar_8972657
